# Meta =======================================================================
title: Shopify Node App - A Shopify App framework built on Node Express and Mongo
description: A Shopify App framework built on Node Express and Mongo. Includes Embedded app SDK and full tutorial.
# Site =======================================================================
name: Shopify Node App
subtitle: A thousand hour headstart in building a Shopify Node App
github_url: https://github.com/Elkfox/Shopify-Node-App
download_url: https://github.com/Elkfox/Shopify-Node-App/archive/master.zip
# demo_url: https://concrete-theme.myshopify.com
# Navigation =================================================================
nav:
  - title: About
    url: '#about'
  - title: 'Getting Started'
    url: '#getting-started'
    childlinks:
    - title: Mongo Setup
      url: '#mongo-setup'
    - title: Ngrok
      url: '#ngrok'
    - title: Shopify Partner Dashboard
      url: '#shopify-partner-dashboard'
    - title: Configuration
      url: '#getting-started-configuration'
  - title: 'Configuration'
    url: '#configuration'
  - title: 'Running'
    url: '#running'
  - title: 'Utils'
    url: '#utils'
  - title: 'Views'
    url: '#views'
  - title: 'Routes'
    url: '#routes'
  - title: 'Applcation Scope'
    url: '#application-scope'
  - title: 'Helper Functions'
    url: '#helper-functions'

# Collections ================================================================
collections:
  documentation:
    title: Documentation
# Build settings =============================================================
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
